spring.application.name=clinic-booking-backend
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/clinic_booking_system
spring.datasource.username=postgres
spring.datasource.password=Son@2005
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- MAIL CONFIGURATION ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mediproadmin@gmail.com 
#Mat khau ung dung (App Password) cua Gmail
spring.mail.password=jtfo ocmb igoa ivqn

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

logging.level.org.springframework.security=DEBUG